// <auto-generated />
namespace CorujaPresentation.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _8th : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_8th));
        
        string IMigrationMetadata.Id
        {
            get { return "201609121326164_8th"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
