// <auto-generated />
namespace CorujaPresentation.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _2nd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_2nd));
        
        string IMigrationMetadata.Id
        {
            get { return "201606102140067_2nd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
